# Generated by Django 5.0.4 on 2024-04-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncodedImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('part_a', models.TextField()),
                ('part_b', models.TextField()),
            ],
        ),
    ]
